---
name: Anchore Syft SBOM scan

"on":
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  Anchore-SBOM:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Scan the repository and upload dependency results
        uses: anchore/sbom-action@bb716408e75840bbb01e839347cd213767269d4a
        with:
          path: .
          artifact-name: sbom.spdx.json
          dependency-snapshot: true
